version: "3.9"
services:
  app:
    build:
      context: .
      args:
        DATABASE_URL: ${DATABASE_URL}
        NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}
        GROQ_API_KEY: ${GROQ_API_KEY}
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
      - GROQ_API_KEY=${GROQ_API_KEY}
    ports:
      - "3000:3000"
